---
  - name: Install apache httpd
    ansible.builtin.apt:
      name: apache2
      state: latest
      update_cache: yes
    become: yes

  - name: Install dependencies
    ansible.builtin.apt:
      pkg:
      - ghostscript 
      - libapache2-mod-php 
      - libapache2-mod-php 
      - mysql-server
      - php
      - php-bcmath
      - php-curl
      - php-imagick
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
      - python3-pymysql
      state: latest
      update_cache: yes
    become: yes
