---
  - name: Install dependencies
    ansible.builtin.apt:
      pkg:
      - mysql-server
      - python3-pymysql
      state: latest
      update_cache: yes
    become: yes

  - name: Create a new database with name '{{ wp_db_name }}'
    community.mysql.mysql_db:
      name: '{{ wp_db_name }}'
      state: present # Vai criar a table se nao existir
      login_unix_socket: /run/mysqld/mysqld.sock
    become: yes

  - name: Create database user with priviles
    community.mysql.mysql_user:
      name: '{{ wp_db_user }}'
      password: '{{ wp_db_pass }}'
      priv: '{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER' # Sempre uppercase
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock # Login root
      host: '{{ item }}'
    with_items:
      - '{{ wp_ip }}'
      - 'localhost'
      - '127.0.0.1'
    become: yes
    # Permitir acesso ao banco de dados para 0.0.0.0
  - name: Replace old hostname with new hostname (requires Ansible >= 2.4)
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
    become: yes
    notify:
      - restart mysqld